### PR TITLE
update support links and info

### PR DESCRIPTION
**Pull request by imrehg**
Superseding #77, based on that conversation update support CTA to GitHub Issues.

Outstanding question: should the Gitter badge be removed from the ReadMe? Or keep it there anyways. It is kept for the moment.

Let me know if any of the text should be rewritten.

### CODE REVIEW

**Comment by alisondavis17** [comment]
@imrehg nice catch. In general, we should have this match the support section of the README in our other repos - such as https://github.com/resin-io/resin-cli

**Comment by imrehg** [comment]
@alisondavis17 so you mean, that don't have a separate gitter channel for this (as it is now), but point to the resin-io gitter (as it is in resin-cli)? And/or the description in the `Support` section should match between projects (I see that the other one has the same approach as this, just not the same words, can fix that)

**Comment by lurch** [comment]
Hmmm, https://github.com/resin-io/resin-cli/blob/master/README.md#support doesn't mention gitter at all, but there _is_ still a "gitter: join chat" button at the top?
Looping in @pimterry too.

**Comment by lurch** [comment]
And should https://gitter.im/resin-io/versionist be "switched off" ?

**Comment by imrehg** [comment]
@lurch was thinking the same way (last message is by us in September) and changed to the resin-io chat here too.

@alisondavis17 rewritten, taking the cue from resin-cli, let me know if there are any language issues!

cc @jviotti

**Comment by alisondavis17** [comment]
lgtm @imrehg thanks!

**Comment by imrehg** [comment]
@lurch what do you think?

**Pull request merged**
