### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alisondavis17**
Change support section to point to Forums instead of Gitter

### CODE REVIEW

**Comment by lurch** [comment]
If we're pointing people at our forums instead of Gitter, should that be accompanied by the creation of a `versionist`-specific forum?

**Comment by alisondavis17** [comment]
Sounds like a good question for @imrehg!

We also don't have to point to the forums at all. We could simply remove Gitter and keep the Support section focused on GitHub issues. The main goal is to remove the expectation of Gitter as a primary Support channel.

**Comment by craig-mulligan** [comment]
I'd don't think it matters too much as long as we have consistency with regards to it all open source projects. @alisondavis17

I suggest we keep it to just gh-issues until the project is more mature? @alisondavis17

**Comment by lurch** [comment]
> as long as we have consistency with regards to it all open source projects. 

Does that mean something similar should also be done for Etcher?

Ping @jviotti and @alexandrosm

**Comment by lurch** [comment]
I just noticed that `versionist` itself is recommending Gitter too when it shows any error messages:
https://github.com/resin-io/versionist/blob/master/bin/cli.js#L40

**Comment by imrehg** [comment]
Closing this and continuing in #98

**Pull request closed without merging**
