### PR TITLE
Mixed types parameters for updateVersionHook

### PR DESCRIPTION
**Pull request by craig-mulligan**
Connects to #69
updateVersionHook now accepts Object of async
functions, and executes each with async's applyEachSeries.

Change-Type: minor

This allows non-proc bots users to tack on functionality with some some simple async functions like [ commit, tag, push ... ].

### CODE REVIEW

**Comment by craig-mulligan** [comment]
@hedss @jviotti any interesting in adding this?

**Comment by jviotti** [comment]
Sounds good to me, but @hedss should give the approval.

**Comment by craig-mulligan** [comment]
@hedss, Please have another quick look at the PR :) 

I've improved the type checking, so now you can pass to [ 'function', 'string' ] to check the types of the config. 

Which let's use do stuff like:
```
updateVersion: [ 'npm', (cwd, version, cb) => (cb()) ]
```

I also made https://github.com/craig-mulligan/versionist-plugins for some personal projects which maybe useful after this is merged.

**Comment by hedss** [comment]
@craig-mulligan Had another look, that's brilliant, this is a fantastic PR. Thanks man!

**Comment by craig-mulligan** [comment]
Arghh, @hedss I didn't realise we had versionbot on this repo now, I've merged manually. What's the best way to correct, do the tagging manually?

**Comment by hedss** [comment]
@craig-mulligan FAIL! ;-) Yeah, `versionist` it then do the tag. :)

**Comment by craig-mulligan** [comment]
@hedss master is protected :) should I could just revert and add the ready for merge tag right? let's see...

**Comment by hedss** [comment]
@craig-mulligan Good point. :) I'll sort it out and publish.

**Comment by hedss** [comment]
@craig-mulligan Done and published.

**Comment by craig-mulligan** [comment]
You da best @hedss 👍

**Pull request merged**
