### PR TITLE
Only output stack trace if DEBUG=versionist (#42)

### PR DESCRIPTION
**Pull request by craig-mulligan**
connects to #42
change-type: patch

### CODE REVIEW

**Comment by lurch** [comment]
This also makes the unit-tests' output much nicer :)

Maybe I'm too much of a Linux-head (and / or maybe I'm not aware of existing NodeJS conventions), but would it make sense to change this to use:
```javascript
  if (process.env.DEBUG === 'true' || process.env.DEBUG === '1') {
```
instead?

**Comment by Page-** [comment]
It might be worth using a module like https://www.npmjs.com/package/debug

**Comment by craig-mulligan** [comment]
@lurch As far as I've seen node convention seems to be `true` rather than `1` but non-node users will use this so we should catch all. 

@Page- All errors are thrown up to `showErrorAndQuit` handler so pretty easy to manage right now. But I agree it would be useful to have levels etc. @lekkas @lurch What do you think?

**Comment by lurch** [comment]
:+1: to supporting both `true` and `1`, but I have no opinion either way on different debug levels. @jviotti ?

**Comment by lekkas** [comment]
I'd be fine with using the `debug` module, which btw doesn't support levels, it will just require a `DEBUG=versionist` (or `DEBUG=*`) convention to print logs in stderr with `console.error`

I'm also totally fine with keeping the current solution which checks directly the `DEBUG` variable, but I'd prefer if we only checked if it's set, rather than comparing with either `true` or `1` (which is what we also use in resin-cli https://github.com/resin-io/resin-cli/blob/master/lib/errors.coffee#L25)

**Comment by jviotti** [comment]
I like the proposal of using the `debug` model and make use of different levels (you can do this by having a convention such as `DEBUG=versionist:<level>`) or use any other similar module.

**Comment by lekkas** [comment]
I think it's an overkill to add debug levels as part of this PR, maybe we can in the future, by first creating a new issue where we can discuss on a way to do it.

**Comment by jviotti** [comment]
Yeah, I agree. The current convention, as far as I've seen, is setting DEBUG to the name of the program (e.g: versionist). `debug` does this out of the box, so I guess we can make a quick, simple integration now, and make use of its more advanced features when we see fit.

**Comment by craig-mulligan** [comment]
@jviotti could you take another look when you are back.

**Comment by jviotti** [comment]
Looks good, I'll approve. The PR title should be changed before merging though, since it still refers to `DEBUG=true`.

**Comment by jviotti** [comment]
Ugh, for some reason I can't approve from mobile :/ I'll do it as soon as I get access to a computer, otherwise consider it approved :)

**Pull request merged**
